Fix rewards accrual
morpho-org/morpho-aavev3-optimizer pull request #860
Opened 2023-06-08 13:01 UTC by Rubilmax

# Pull Request

## Issue(s) fixed

This pull request:

- fixes https://github.com/spearbit-audits/review-morpho-june/issues/28#issuecomment-1582196383

2023-06-08 15:42 UTC, Tristan22400 approved these changes, later dismissed

2023-06-08 17:54 UTC, pakim249CAL commented on src/MorphoInternal.sol
> +    function _updateInDS(address underlying, address user, uint256 onPool, uint256 inP2P, bool demoting, bool supply)
This new design seems unnecessarily complex and mistake prone. I propose that we simply split up the _updateInDS function to _updateSupplyInDS and _updateBorrowInDS

2023-06-09 06:18 UTC, Rubilmax commented on src/MorphoInternal.sol
> +    function _updateInDS(address underlying, address user, uint256 onPool, uint256 inP2P, bool demoting, bool supply)
I also prefer that for many reasons, but wanted to stick to the previous design. I'll apply your suggestion!

2023-06-09 11:00 UTC, Tristan22400 submitted a review, later dismissed

2023-06-09 12:50 UTC, MerlinEgalite approved these changes
Changes look good but with lot's of redundant code. Not sure that internalizing them would be better though

2023-06-09 13:53 UTC, QGarchery approved these changes, later dismissed
LGTM

2023-06-09 15:02 UTC, pakim249CAL submitted a review, later dismissed

2023-06-09 16:49 UTC, MerlinEgalite requested changes
Requesting changes to prevent merge

2023-06-19 05:48 UTC, pakim249CAL approved these changes, later dismissed

2023-06-19 09:33 UTC, Tristan22400 commented on src/PositionsManagerInternal.sol
> +            onBehalf, _market[underlying].aToken, collateralBalance + marketBalances.scaledPoolSupplyBalance(onBehalf)
I do not understand why here we use the getters.

2023-06-19 09:33 UTC, Tristan22400 commented on src/PositionsManagerInternal.sol
> +            onBehalf, _market[underlying].aToken, collateralBalance + marketBalances.poolSuppliers.valueOf[onBehalf]
and why there we are directly reading the value without using the getters.

2023-06-19 09:54 UTC, MerlinEgalite commented on src/PositionsManagerInternal.sol
> +            onBehalf, _market[underlying].aToken, collateralBalance + marketBalances.poolSuppliers.valueOf[onBehalf]
will update

2023-06-19 10:37 UTC, Rubilmax commented on src/PositionsManagerInternal.sol
> +            onBehalf, _market[underlying].aToken, collateralBalance + marketBalances.scaledPoolSupplyBalance(onBehalf)
Why shouldn't we?
The goal of getters is to factorize code to avoid forgetting about an edge case

2023-06-19 12:08 UTC, Tristan22400 approved these changes

2023-06-19 12:29 UTC, Rubilmax reviewed
LGTM! But pending because rewards are not available on mainnet so upgrade is not yet required.

2023-06-19 13:23 UTC, makcandrov approved these changes

2025-11-03 23:47 UTC, 7fantasy7 approved these changes

2025-11-10 09:45 UTC, QGarchery commented
Closing this PR as optimizers are deprecated now

2025-11-10 09:45 UTC, closed without merging